    networks:
      derivasset-demo-network:

    services:
      db-java:
        image: 'postgres:latest'
        environment:
          - 'POSTGRES_DB=library-management-java'
          - 'POSTGRES_USER=dbuser'
          - 'POSTGRES_PASSWORD=dbpassword'
        networks:
          - derivasset-demo-network
        ports:
          - '5432'
        healthcheck:
          test: 'pg_isready -d library-management-java -U dbuser'
      db-go:
        image: 'postgres:latest'
        environment:
          - 'POSTGRES_DB=library-management-go'
          - 'POSTGRES_USER=dbuser'
          - 'POSTGRES_PASSWORD=dbpassword'
        networks:
          - derivasset-demo-network
        ports:
          - '5432'
        healthcheck:
          test: 'pg_isready -d library-management-go -U dbuser'

      redis:
        image: 'redis:latest'
        hostname: 'redis-host'
        networks:
          - derivasset-demo-network
        ports:
          - '6379'

      redis-commander:
        image: 'rediscommander/redis-commander:latest'
        depends_on:
          - redis
        environment:
          - 'REDIS_HOSTS=redis-host'
        ports:
          - '8081:8081'
        networks:
          - derivasset-demo-network

      pgadmin:
        image: 'dpage/pgadmin4:latest'
        depends_on:
          - db-java
          - db-go
        environment:
          - 'PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com'
          - 'PGADMIN_DEFAULT_PASSWORD=password'
          - 'PGADMIN_LISTEN_PORT=8082'
        ports:
          - '8082:8082'
        networks:
          - derivasset-demo-network

      backend-java:
        build:
          context: ./backend-java
        depends_on: 
          db-java:
            condition: service_healthy
        networks:
          - derivasset-demo-network
        ports:
          - "8083:8080"
        

      backend-go:
        build:
          context: ./backend-go
        depends_on: 
          db-go:
            condition: service_healthy
        networks:
          - derivasset-demo-network
        ports:
          - "8084:8080"

      frontend:
        build:
          context: ./frontend
        depends_on:
          - backend-java
          - backend-go
        ports:
          - "3000:4173"
        networks:
          - derivasset-demo-network